version: '3'

services:
  db:
    image: postgres:15.3
    container_name: prompts-test
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prompts
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tables.sh:/docker-entrypoint-initdb.d/tables.sh

volumes:
  postgres_data: